- type: entity
  parent: BlueshieldAmmunitionBox
  id: BlueshieldAmmunitionBoxFilled
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: MagazineBoxMagnum
      amount: 2
    - id: MagazineBoxMagnumRubber
      amount: 2
    - id: MagazineBoxMagnumIncendiary
    - id: MagazineBoxMagnumUranium
    - id: MagazineBoxMagnumAP
    - id: MagazineBoxMagnumShrapnel
      amount: 2
    - id: MagazineBoxMagnumFlash
    - id: MagazineBoxMagnumEnsnaring
    # - id: MagazineBoxMagnumEMP
